service: lambda-pdfxs3

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-plugin-existing-s3
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "*"
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  environment: ${file(env.yml):${self:provider.stage}}

package:
  exclude:
    - demo/**
    - node_modules/**
    - tests/**
    - .babelrc
    - .d*
    - .e*
    - .g*
    - .git/**
    - .DS_*
    - docker*.yml
    - Dockerfile
    - build-*.sh

functions:
  pdfHandler:
    handler: handler.pdfHandler
    events:
      - existingS3:
            bucket: ${file(env.yml):${self:provider.stage}.FROMBUCKET}
            events:
              - s3:ObjectCreated:*
            rules:
              - prefix: uploads/
              - suffix: .pdf
